name: Release

on:
  push:
    branches: [main, beta]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
        registry-url: https://npm.pkg.github.com/
        scope: "@Duahau1"
    - name: Install dependencies
      run: npm ci
    - name: Install semantic-release extra plugins
      run: npm install --save-dev @semantic-release/changelog @semantic-release/git
    - name: Build
      run: npm run build
    - name: Release
      run: npx semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
